<?php
/**
 * Created by PhpStorm.
 * User: Musa ATALAY
 * Date: 7.08.2015
 * Time: 18:12
 */

/**
 * Connection Settings
 */
const ARAS_API_HOST = "https://appls-srv.araskargo.com.tr";
const ARAS_API_TARGET = "arascargoservice/arascargoservice.asmx";
const ARAS_API_PORT = 443;
const ARAS_API_TIMEOUT = 60;

const ARAS_API_USERNAME = "tibetpazarlama";
const ARAS_API_PASSWORD = "tibetpazarlama";
const ARAS_API_CUSTOMER_KEY = 1514941931551;