<?php
/**
 * author: Sebahattin Çatal
 * website: www.sebahattincatal.com
 */

session_start(); ob_start();
include("include.php");
oturum_koru();

/** Error reporting */
error_reporting(E_ALL);
ini_set('display_errors', TRUE);
ini_set('display_startup_errors', TRUE);
date_default_timezone_set('Europe/Istanbul');
if (PHP_SAPI == 'cli')
    die('This example should only be run from a Web Browser');
/** Include PHPExcel */
require_once dirname(__FILE__) . '/PHPExcel.php';

function exportExcel($filename='ExportExcel',$columns=array(),$data=array(),$replaceDotCol=array()){

    // Create new PHPExcel object
    $objPHPExcel = new PHPExcel();
    // Set document properties
    $objPHPExcel->getProperties()->setCreator("AdgetClub Panel")
        ->setLastModifiedBy("Adget Club Panel")
        ->setTitle("Office 2007 XLSX AdgetClub Panel Kargo Export")
        ->setSubject("Office 2007 XLSX AdgetClub Panel Kargo Export")
        ->setDescription("AdgetClub Panel Kargo Export Office 2007 XLSX, generated by AdgetClub Panel using PHP.")
        ->setKeywords("AdgetClub Panel Kargo Export")
        ->setCategory("AdgetClub Panel Kargo Export");

    // Redirect output to a client’s web browser (Excel5)
    header('Content-Type: application/vnd.ms-excel');
    header('Content-Disposition: attachment;filename="'.$filename.'.xls"');
    header('Cache-Control: max-age=0');
    // If you're serving to IE 9, then the following may be needed
    header('Cache-Control: max-age=1');
    // If you're serving to IE over SSL, then the following may be needed
    header ('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
    header ('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT'); // always modified
    header ('Cache-Control: cache, must-revalidate'); // HTTP/1.1
    header ('Pragma: public'); // HTTP/1.0

    $say=count($columns);

    $alphas = range('A', 'Z');

    foreach($columns AS $index => $value){

        // Add some data
        $objPHPExcel->setActiveSheetIndex(0)->setCellValue($alphas[$index]."1", $value);

        foreach($data AS $i => $d){

            $objPHPExcel->setActiveSheetIndex(0)->setCellValue($alphas[$index].($i+2), $d[$index]);

        }

    }

    // Rename worksheet
    $objPHPExcel->getActiveSheet()->setTitle($filename);

    // Set active sheet index to the first sheet, so Excel opens this as the first sheet
    $objPHPExcel->setActiveSheetIndex(0);

    $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
    $objWriter->save('php://output');

    exit;
}

$replaceDotCol=array(3);


/* Sütun Başlıkları */
$columns=array(
    'Ad Soyad',
    'Telefon',
    'urun',
    'fiyat',
    'Adet',
    'il',
    'ilce',
    'Adres'
);

function part($t){
    $xx =explode("/",$t);
    $k=  $xx["2"]."-".$xx["1"]."-".$xx["0"];
    return $k;
}


$tarih = mysql_real_escape_string(strip_tags($_GET["tarih"]));
if(empty($tarih)){
    exit();
}

$tarih = part($_GET["tarih"]);

$d = $db->get_results("SELECT * FROM siparisler where satis_tarihi between '".$tarih." 00:00:00' AND '".$tarih." 23:59:59' AND (siparis_durumu = 6 OR siparis_durumu = 7 OR siparis_durumu = 8) ".$sql_statu."  order by satis_tarihi ASC ");
if($d){
    foreach ($d as  $value) {
        /* Satır Verileri */
        $data[]=array(
            $value->ad_soyad,
            $value->Telefon_no,
            $value->urunun_adi,
            $value->fiyat,
            $value->urun_adeti,
            $value->il,
            $value->ilce,
            $value->adres,

        );
    }}


$DosyaAdi = "kaliteden_gecenler-".rand(1,99999);

exportExcel($DosyaAdi,$columns,$data,$replaceDotCol);

exit;